trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  subscriptionId: '8e08d5d6-7dbc-4fe5-8da3-8f773ce909c7'
  resourceGroupApps: 'haneensouthafricanorth'
  backendImage: 'nginx:latest'
  backendIngressTraffic: 'external'
  backendRevisionSuffix: 'nginx-test'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Deploy Container Apps
  inputs:
    azureResourceManagerConnection: 'sc-retailapp-prd'
    subscriptionId: '$(subscriptionId)'
    resourceGroupName: '$(resourceGroupApps)'
    location: 'northeurope'
    csmFile: 'ContainerApps.json'
    csmParametersFile: 'ContainerApps.parameters.json'
    overrideParameters: >-
      -backendImage $(backendImage)
      -backendIngressTraffic $(backendIngressTraffic)
      -backendRevisionSuffix $(backendRevisionSuffix)
    deploymentMode: 'Incremental'
    deploymentName: '$(Build.Buildnumber)-$(System.JobAttempt)'
