trigger:
- main

variables:
  subscriptionId: 'a9418ddc-91db-4d80-9945-d09bb8fcdd07'
  resourceGroupApps: 'haneenweu'
  backendImage: 'nginx:latest'
  backendIngressTraffic: 'external'
  backendRevisionSuffix: 'nginx-test'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
inputs:
  azureResourceManagerConnection: haneenarm
  subscriptionId: $(subscriptionId)
  resourceGroupName: $(resourceGroupApps)
  location: northeurope
  csmFile: "ContainerApps.json"
  csmParametersFile: ContainerApps.parameters.json
  overrideParameters: >-
    -backendImage $(backendImage) -backendIngressTraffic $(backendIngressTraffic) -backendRevisionSuffix $(backendRevisionSuffix)
  deploymentMode: Incremental
  deploymentName: "$(Build.Buildnumber)-$(System.JobAttempt)"
displayName: Deploy Container Apps
