trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  resourceGroup: haneenweu
  containerAppName: acahaneen
  environmentName: managedEnvironment-haneenweu-8ec8
  location: westeurope
  imageName: nginx:latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'a9418ddc-91db-4d80-9945-d09bb8fcdd07'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      # Create Container App if it doesn't exist
      az containerapp create \
        --name ${{ variables.containerAppName }} \
        --resource-group ${{ variables.resourceGroup }} \
        --environment ${{ variables.environmentName }} \
        --image ${{ variables.imageName }} \
        --target-port 80 \
        --ingress 'external' \
        --revision-suffix nginxv1 \
        --query-properties configuration.ingress.external=true \
        --transport http
    displayName: 'Deploy Nginx to Azure Container Apps'
